export const suggestions = [
  {label: 'COURSE:  Algorithms, Part II'},
  {label: 'COURSE:  Applied Data Science with Python'},
  {label: 'COURSE:  AWS Developer: Optimizing on AWS'},
  {label: 'COURSE:  Computer Application in Economic Management'},
  {label: 'COURSE:  Essay Writing'},
  {label: 'COURSE:  First Nights'},
  {label: 'COURSE:  Fundamentals of Graphic Design'},
  {label: 'COURSE:  HTML5 Coding Essentials and Best Practices'},
  {label: 'COURSE:  Introducción al desarrollo de videojuegos con Unity'},
  {label: 'COURSE:  Just Money: Banking as if Society Mattered'},
  {label: 'COURSE:  L innovazione sociale per il patrimonio culturale'},
  {label: 'COURSE:  Laboratorio di Programmazione'},
  {label: 'COURSE:  Master Python'},
  {label: 'COURSE:  Microsoft Bot Framework and Conversation as a Platform'},
  {label: 'COURSE:  Neural Networks and Deep Learning'},
  {label: 'MAJOR:  Architecture'},
  {label: 'MAJOR:  Art & Culture'},
  {label: 'MAJOR:  Chemistry'},
  {label: 'MAJOR:  Computer Science'},
  {label: 'MAJOR:  Design'},
  {label: 'MAJOR:  Economics & Finance'},
  {label: 'MAJOR:  Engineering'},
  {label: 'MAJOR:  History'},
  {label: 'MAJOR:  Language'},
  {label: 'MAJOR:  Law'},
  {label: 'MAJOR:  Math'},
  {label: 'MAJOR:  Music'},
  {label: 'MAJOR:  Social Science'},
  {label: 'SKILL:  Python'},
  {label: 'SKILL:  Java'},
  {label: 'SKILL:  Algorithm'},
  {label: 'SKILL:  Coding'},
];
